### ISSUE TITLE
OpenWeave, Openthread and the 'Service' nRF52840

### ISSUE THREAD

**Issue by Dayna-A** [openweave/openweave-core#340]
Hello OpenWeave Team, 
Is there anywhere we can access the code for this codelab https://kiosk-dot-codelabs-site.appspot.com/codelabs/device-to-device-openweave/index.html?index=..%2F..index#1 ? 
Or even just the code for the border router in that setup?
We are hoping to understand more about putting it all together and struggling to find concrete documentation. 
We have noticed that the documentation often refers to connecting to 'the service'.
Does this refer only to a nest service? Or is there a test 'service' application that we can connect our devices to? 
Thanks for your help!

**Comment by gerickson** [comment]
@Dayna-A, I am hopeful that @robszewczyk can help with the code lab piece.

Regarding the "the service", yes, this refers to the Google Nest service. There have historically been some internal-only test services; however, there is nothing today that's broadly and publicly available to the open developer community.

**Comment by jaylogue** [comment]
>
> @gerickson <https://github.com/gerickson> Would you be willing to answer
> a few more questions for me in the meantime?
> 1st - Should I be able to connect a device flashed with the lock example
> via the DeviceManager tool?
> 2nd - Can the Happy tool connect to real nodes and networks as well as
> simulated ones?
> Thank you!


I can take a stab at these.

1) Yes.  Presuming that the device is in a completely unprovisioned state,
you will need to use BLE to establish a connection.  This can be
accomplished by running the Weave Device Manager shell on a Mac, or a Linux
machine with a suitable BlueZ compatible BLE interface.

Once the device boots and begins advertising, one can connect to it using
the following device manager commands:

ble-scan
ble-scan-connect *<device-ble-name>*
connect --ble --pairing-code
*<pairing-code>*


The device's BLE name and pairing code can be found in the logs printed by
the device at boot.

2) The Happy tool includes a feature for providing live internet
connectivity to simulated devices via the host's primary interface.  Since
Happy is based on Linux's virtual networking functionality internally
(virtual bridges, network namespace, veth devices, etc.), in theory it
would be possible to create more complicated hybrid topologies.  However
the Happy tool provides no options to accomplish this.

--Jay

Jay Logue
The OpenWeave Team
jaylogue@google.com

**Comment by Dayna-A** [comment]
Thank you @jaylogue this helps very much!
