### ISSUE TITLE
Nest weave sucks - range issues

### ISSUE THREAD

**Issue by sebastienbo** [openweave/openweave-core#407]
Hi,

I feel very frustrated with nest weave.
When I used zwave I had the benefit of never having network issues, becausse when a device was out of range, the zwave protocol relayed the message untill it got to the recipient device that wass out of range.

But with my nest thermostat I notice that 12 meters is not enough to contact my thermostat wirelessly (which is a requirement for the opentherm...doesn't work wired...)
However my whole house is full of nest protect smokedetectors, why do they not relay between my thermostat and heat link ... and why does opentherm does not work with the wired setup? and why can't the heat link connect via wifi.

Is there some nest weave extender available for such a situations or is it just crap and do i need to look for another solution/brand?

**Comment by jaylogue** [comment]
Hi Sebastien,

I'm sorry to hear you're frustrated with the performance of your Nest Thermostat.  Unfortunately, I don't think the developers of OpenWeave can help you.  OpenWeave is a communication framework that is used by Nest products to carry out application-layer communication between devices.  It sits above network layers like WiFi and Thread.  As such, it is subject to the range limitations inherent in those technologies, as well as any local effects arising from the environment (e.g. physical obstructions).

Rather than filing an issue here, I would suggest reaching out to the Google Nest support team at [https://nest.com/support/contact-us/](https://nest.com/support/contact-us/).  They should be able to help assess the issues you're seeing and find a solution.

Thank you.

**Comment by sebastienbo** [comment]
Well my point was, that the waring protocol would require enhancements by
using neighbours to send messages to a destination, jut like zwave can.

Contact nest didn't help because they told that the caring protocol
openweave doesn't allow such feature and they use open weave.
basically they are saying its openweavess limitation, not nest.

Met vriendelijke Groeten,

*Sébastien Boelpaep*
Platanenlaan 38
1600 Sint-Pieters-Leeuw
Belgie

0476 60 57 03

ATTENTION:
This e-mail is private, confidential and intended only for the
addressee(s). It shall not constitute any commitment for Logistix BVBA
or it's sender unless expressly agreed otherwise in a written
agreement. If you are not the intended recipient, please inform the
sender of this message and delete it immediately.

**Comment by jaylogue** [comment]
> Well my point was, that the waring protocol would require enhancements by
> using neighbours to send messages to a destination, jut like zwave can.

Thread has this feature as well.  Again, this is a feature of the underlying network technology, not of the application layer.  (If you're interested, you can read more about Thread at [openthread.io/guides](https://openthread.io/guides)).

> Contact nest didn't help because they told that the caring protocol
> openweave doesn't allow such feature and they use open weave.
> basically they are saying its openweavess limitation, not nest.

It is unfortunate that they are confused in this way.  If you have a contact for who you spoke with, I can investigate further.

I think the fundamental problem you're facing is that Nest does not offer a Thread mesh router product that can act as a range extender for your thermostat.  The Nest Connect product does exactly this.  Unfortunately its not available for sale in the EU.
