### ISSUE TITLE
Remove autotools-generated build artifacts from openweave-core

### ISSUE THREAD

**Issue by samhansen** [openweave/openweave-core#422]
It is proposed that the autotools/autoconf-generated artifacts (e.g. configure, */Makefile.in, etc...) be removed from the repository.  The bootstrap script would be used to regenerate these files upon repository clone.

**Comment by gerickson** [comment]
No fundamental opposition to this since many other autotools-based projects take this approach, only generating such artifacts when they create a distribution archive snapshot.

However, has an assessment been done to how this will impact downstream projects and is an information / documentation campaign intended to go along with this proposed change to help guide those projects on how to navigate the change (as straightforward as it may be)?

**Comment by jaylogue** [comment]
@robszewczyk This is effectively done, right?

**Comment by robszewczyk** [comment]
@jaylogue -- that's right.  I'll mark this issue as closed
